// Copyright 2021 The Matrix.org Foundation C.I.C.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package lb

var cborv1Keys = map[string]int{
	"event_id":                    1,
	"type":                        2,
	"content":                     3,
	"state_key":                   4,
	"room_id":                     5,
	"sender":                      6,
	"user_id":                     7,
	"origin_server_ts":            8,
	"unsigned":                    9,
	"prev_content":                10,
	"state":                       11,
	"timeline":                    12,
	"events":                      13,
	"limited":                     14,
	"prev_batch":                  15,
	"transaction_id":              16,
	"age":                         17,
	"redacted_because":            18,
	"next_batch":                  19,
	"presence":                    20,
	"avatar_url":                  21,
	"account_data":                22,
	"rooms":                       23,
	"join":                        24,
	"membership":                  25,
	"displayname":                 26,
	"body":                        27,
	"msgtype":                     28,
	"format":                      29,
	"formatted_body":              30,
	"ephemeral":                   31,
	"invite_state":                32,
	"leave":                       33,
	"third_party_invite":          34,
	"is_direct":                   35,
	"hashes":                      36,
	"signatures":                  37,
	"depth":                       38,
	"prev_events":                 39,
	"prev_state":                  40,
	"auth_events":                 41,
	"origin":                      42,
	"creator":                     43,
	"join_rule":                   44,
	"history_visibility":          45,
	"ban":                         46,
	"events_default":              47,
	"kick":                        48,
	"redact":                      49,
	"state_default":               50,
	"users":                       51,
	"users_default":               52,
	"reason":                      53,
	"visibility":                  54,
	"room_alias_name":             55,
	"name":                        56,
	"topic":                       57,
	"invite":                      58,
	"invite_3pid":                 59,
	"room_version":                60,
	"creation_content":            61,
	"initial_state":               62,
	"preset":                      63,
	"servers":                     64,
	"identifier":                  65,
	"user":                        66,
	"medium":                      67,
	"address":                     68,
	"password":                    69,
	"token":                       70,
	"device_id":                   71,
	"initial_device_display_name": 72,
	"access_token":                73,
	"home_server":                 74,
	"well_known":                  75,
	"base_url":                    76,
	"device_lists":                77,
	"to_device":                   78,
	"peek":                        79,
	"last_seen_ip":                80,
	"display_name":                81,
	"typing":                      82,
	"last_seen_ts":                83,
	"algorithm":                   84,
	"sender_key":                  85,
	"session_id":                  86,
	"ciphertext":                  87,
	"one_time_keys":               88,
	"timeout":                     89,
	"recent_rooms":                90,
	"chunk":                       91,
	"m.fully_read":                92,
	"device_keys":                 93,
	"failures":                    94,
	"device_display_name":         95,
	"prev_sender":                 96,
	"replaces_state":              97,
	"changed":                     98,
	"unstable_features":           99,
	"versions":                    100,
	"devices":                     101,
	"errcode":                     102,
	"error":                       103,
	"room_alias":                  104,
	"server":                      105,
	"version":                     106,
	"method":                      107,
	"old_verify_keys":             108,
	"server_name":                 109,
	"valid_until_ts":              110,
	"verify_keys":                 111,
	"expired_ts":                  112,
	"key":                         113,
	"server_keys":                 114,
	"destination":                 115,
	"edus":                        116,
	"pdus":                        117,
	"edu_type":                    118,
	"auth_chain":                  119,
	"earliest_events":             120,
	"latest_events":               121,
	"limit":                       122,
	"min_depth":                   123,
	"auth_chain_ids":              124,
	"pdu_ids":                     125,
	"invite_room_state":           126,
	"invites":                     127,
	"mxid":                        128,
	"signed":                      129,
	"aliases":                     130,
	"total_room_count_estimate":   131,
	"canonical_alias":             132,
	"guest_can_join":              133,
	"num_joined_members":          134,
	"world_readable":              135,
	"push":                        136,
	"currently_active":            137,
	"last_active_ago":             138,
	"status_msg":                  139,
	"ts":                          140,
	"master_key":                  141,
	"self_signing_keys":           142,
	"stream_id":                   143,
	"keys":                        144,
	"algorithms":                  145,
	"usage":                       146,
	"deleted":                     147,
	"prev_id":                     148,
	"master_keys":                 149,
	"self_signing_key":            151,
}
